/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cliente;
import clases.Computadores;
import clases.Factura;
import clases.Helper;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.*; 
import java.awt.print.*; 
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
/**
 *
 * @author jpayares4
 */
public class AgregarFactura extends javax.swing.JDialog {

    /**
     * Creates new form Agregar
     */
    String rutaC, rutaP, rutaF,ruta;

    ObjectOutputStream salida;
    ArrayList<Factura> factura;
    int aux = 0;

    public static String fechaActual(){
      Date fecha=new Date();
      SimpleDateFormat formatoFecha=new SimpleDateFormat("DD/MM/YYYY");
      return formatoFecha.format(fecha);
    }
    public AgregarFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtFecha.setText(fechaActual());
        ruta = "src/datos/factura.txt";
        JButton botonesH[] = {cmdBuscar, cmdCancelar, cmdGuardar};
        JButton botonesD[] = {cmdEliminar};

   
        rutaP = "src/datos/computadores.txt";
        rutaC = "src/datos/clientes.txt";
        rutaF = "src/datos/factura.txt";
        Helper.llenarComboClientes(cmbCliente, rutaC);
        Helper.llenarComboEquipo(cmbEquipo, rutaP);
        try {
            factura = Helper.traerDatos(rutaF);
            salida = new ObjectOutputStream(new FileOutputStream(rutaF));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, factura);
        Helper.llenarTablaFactura(tblFactura, rutaF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCodigoFactura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNfactura = new javax.swing.JTextField();
        cmbEquipo = new javax.swing.JComboBox();
        cmbPago = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cmbCliente = new javax.swing.JComboBox();
        txtFecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGREGAR CARROS");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "N°factura", "Cliente", "Pagos", "Equipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFactura);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 190));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, 570, 240));
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477426732_floppy.png"))); // NOI18N
        cmdGuardar.setBorder(null);
        cmdGuardar.setContentAreaFilled(false);
        cmdGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477426736_floppy.png"))); // NOI18N
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477427251_free-27.png"))); // NOI18N
        cmdEliminar.setBorder(null);
        cmdEliminar.setContentAreaFilled(false);
        cmdEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477427253_free-27.png"))); // NOI18N
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));

        cmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477427499_Cancel.png"))); // NOI18N
        cmdCancelar.setBorder(null);
        cmdCancelar.setContentAreaFilled(false);
        cmdCancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477427501_Cancel.png"))); // NOI18N
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        cmdBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1478031465_search.png"))); // NOI18N
        cmdBuscar.setBorder(null);
        cmdBuscar.setContentAreaFilled(false);
        cmdBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1478031466_search.png"))); // NOI18N
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1478031573_Log Out.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1478031574_Log Out.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 120, 190));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BOLETA DE VENTAS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 29, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 255));
        jLabel10.setText("R.U.C. 101553005368");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 1, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 255));
        jLabel11.setText("0001.");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 71, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("N°");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 65, -1, -1));

        lblCodigoFactura.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCodigoFactura.setForeground(new java.awt.Color(255, 0, 0));
        lblCodigoFactura.setText("000000");
        lblCodigoFactura.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCodigoFacturaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(lblCodigoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 65, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N° factura:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cliente:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Formas de pago:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtNfactura.setOpaque(false);
        txtNfactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNfacturaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, -1));

        cmbEquipo.setOpaque(false);
        jPanel2.add(cmbEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 20));

        cmbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Cheque", "Tarjeta", " " }));
        jPanel2.add(cmbPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 200, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1478031465_search.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1478031466_search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        cmbCliente.setOpaque(false);
        jPanel2.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, 20));

        txtFecha.setOpaque(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Equipo:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 190));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FACTURA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/obr (1).png"))); // NOI18N
        jLabel13.setText("jLabel4");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 500, 360));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpapers.JPG"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        setSize(new java.awt.Dimension(703, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed

        String fecha, auxEquipo, auxCliente, nfactura, fpago, codigo, cedula;
        int indice, indice2;
        Computadores equipo;
        Cliente cliente;

        fecha = txtFecha.getText();
        nfactura = txtNfactura.getText();
        fpago = cmbPago.getSelectedItem().toString();
        auxEquipo = cmbEquipo.getSelectedItem().toString();
        auxCliente = cmbCliente.getSelectedItem().toString();

          if (txtNfactura.getText().isEmpty()) {
            getToolkit().beep();
            Helper.mensaje(this, "Digite el numero de la Factura", 3);
            txtNfactura.requestFocusInWindow();

        } else {
        indice = auxEquipo.indexOf("-") - 1;
        indice2 = auxCliente.indexOf("-") - 1;
        codigo = auxEquipo.substring(0, indice);
        cedula = auxCliente.substring(0, indice2);
        ArrayList<Factura> facturaModificada;
        equipo = Helper.traerComputadoresCodigo(codigo, rutaP);
        cliente = Helper.traerClienteCedula(cedula, rutaC);
        try {
            if (aux == 0) {

                Factura f = new Factura(fecha, nfactura, fpago, cliente, equipo);

                f.guardar(salida);

            } else {
                facturaModificada = Helper.modificarFactura(rutaF, fecha, nfactura, fpago, cliente, equipo);
                salida = new ObjectOutputStream(new FileOutputStream(rutaF));
                Helper.volcado(salida, facturaModificada);
                aux = 0;
                Helper.mensaje(this, "Factura Actualizada Correctamente!", 1);
            }
        } catch (IOException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }

        Helper.llenarTablaFactura(tblFactura, rutaF);

        cmbPago.setSelectedIndex(0);

        JButton botonesH[] = {cmdBuscar, cmdCancelar};
        JButton botonesD[] = {cmdEliminar, cmdGuardar};
          }
       
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        txtNfactura.setText("");
        txtFecha.setText("");
        
      
        cmbPago.setSelectedIndex(0);

        txtNfactura.requestFocusInWindow();
        JButton botonesH[] = {cmdBuscar, cmdCancelar};
        JButton botonesD[] = {cmdEliminar, cmdGuardar};

      
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void tblFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacturaMouseClicked
        int i;
        String auxEquipo ,auxCliente;
        Factura c;
        Cliente cliente;
        Computadores equipo;
        ArrayList<Factura> factura = Helper.traerDatos(rutaF);
        i = tblFactura.getSelectedRow();

        c = factura.get(i);

        txtNfactura.setText(c.getNfactura());
        cmbPago.getSelectedItem().toString();
        cliente = c.getCliente();
        equipo = c.getEquipo();
        auxEquipo = equipo.getCodigo() + " -- " + equipo.getProcesador() + " -- " + equipo.getPrecio();
        auxCliente= cliente.getCedula()+ " -- " + cliente.getTelefono()+ " -- " + cliente.getDireccion();
        cmbPago.setSelectedItem(auxEquipo);
        aux = 1;
        
        JButton botonesH[] = {cmdEliminar, cmdGuardar, cmdCancelar};
        JButton botonesD[] = {cmdBuscar};

            
    }//GEN-LAST:event_tblFacturaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListadoPorMarca lps = new ListadoPorMarca(null, true);
        lps.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblCodigoFacturaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCodigoFacturaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCodigoFacturaAncestorAdded

    private void txtNfacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNfacturaKeyTyped
       char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNfacturaKeyTyped

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
         int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar a esta Factura ?", "Eliminar", JOptionPane.YES_NO_OPTION);

        ArrayList<Factura> factura = Helper.traerDatos(ruta);
        if (op == JOptionPane.YES_OPTION) {
            i = tblFactura.getSelectedRow();
           factura.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AgregarFactura.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AgregarFactura.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, factura);
            Helper.llenarTablaFactura(tblFactura, ruta);
            txtNfactura.setText("");
        txtFecha.setText("");
      
      
        cmbPago.setSelectedIndex(0);

        txtNfactura.requestFocusInWindow();
        }

    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
      
        
        
        
    }//GEN-LAST:event_txtFechaActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String nfactura, auxEquipo, auxCliente, cedula;
        Computadores equipo;
        Cliente cliente;

        nfactura = txtNfactura.getText();
        Factura c;
        if (txtNfactura.getText().isEmpty()) {
            getToolkit().beep();
            Helper.mensaje(this, "Digite Numero dela factura", 3);
            txtNfactura.requestFocusInWindow();
        } else {

            if (Helper.buscarFacturaNfactura(nfactura, rutaF)) {
                c = Helper.traerFacturaNfactura(nfactura, rutaC);
                txtNfactura.setText(c.getNfactura());
                equipo = c.getEquipo();
                cliente = c.getCliente();
                auxEquipo = equipo.getCodigo() + " -- " + equipo.getMarca() + " -- " + equipo.getPrecio();
                auxCliente = cliente.getCedula() + " -- " + cliente.getNombre() + " -- " + cliente.getTelefono();
                cmbPago.setSelectedItem(auxEquipo);
                aux = 1;
            } else {
                txtNfactura.requestFocusInWindow();
                aux = 0;
            }
            JButton botonesH[] = {cmdGuardar, cmdCancelar};
            JButton botonesD[] = {cmdBuscar, cmdEliminar};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarFactura dialog = new AgregarFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JComboBox cmbEquipo;
    private javax.swing.JComboBox<String> cmbPago;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigoFactura;
    private javax.swing.JTable tblFactura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNfactura;
    // End of variables declaration//GEN-END:variables
}
