/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Computadores;
import clases.Helper;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import java.awt.*;
import java.awt.print.*;
import java.util.StringTokenizer;

/**
 *
 * @author rmorales1
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    String ruta;

    public Inicio() {

        initComponents();
        ruta = "src/datos/computadores.txt";
        ImageIcon a = new ImageIcon("src/imagenes/jorge.png");
        setIconImage(a.getImage());
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        mnAgregar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        mnReportes = new javax.swing.JMenu();
        mnListados = new javax.swing.JMenu();
        mnListadoPersonas = new javax.swing.JMenuItem();
        mnListadoPorSexo = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnCantidades = new javax.swing.JMenu();
        mnCantidadPersonasIngresadas = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setText("jLabel2");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477688515_youtube.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/obr (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 500, 360));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpapers.JPG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setOpaque(false);

        mnOpciones.setBackground(new java.awt.Color(0, 0, 0));
        mnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415422_f-optimization_256.png"))); // NOI18N
        mnOpciones.setText("Opciones");
        mnOpciones.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        mnOpciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477687431_Settings.png"))); // NOI18N
        mnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpcionesActionPerformed(evt);
            }
        });

        mnAgregar.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        mnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415512_computer.png"))); // NOI18N
        mnAgregar.setText("Agregar Computadores");
        mnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        mnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnAgregar);

        jMenuItem3.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415548_user-group.png"))); // NOI18N
        jMenuItem3.setText("Agrgar Clientes");
        jMenuItem3.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnOpciones.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415588_user-id.png"))); // NOI18N
        jMenuItem5.setText("AgregarVendedores");
        jMenuItem5.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnOpciones.add(jMenuItem5);

        jMenuItem4.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem4.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415701_08.png"))); // NOI18N
        jMenuItem4.setText("Factura");
        jMenuItem4.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnOpciones.add(jMenuItem4);
        mnOpciones.add(jSeparator1);

        mnSalir.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477427499_Cancel.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.setBorder(new javax.swing.border.SoftBevelBorder(0));
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnOpciones.add(mnSalir);

        jMenuBar1.add(mnOpciones);

        mnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415466_6.png"))); // NOI18N
        mnReportes.setText("Reportes");
        mnReportes.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N

        mnListados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mnListados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477687710_preferences-contact-list.png"))); // NOI18N
        mnListados.setText("Listados");
        mnListados.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N

        mnListadoPersonas.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        mnListadoPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477687978_vector_65_14.png"))); // NOI18N
        mnListadoPersonas.setText("Listado de Computadores");
        mnListadoPersonas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mnListadoPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListadoPersonasActionPerformed(evt);
            }
        });
        mnListados.add(mnListadoPersonas);

        mnListadoPorSexo.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        mnListadoPorSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477688032_Tick_Mark_Circle.png"))); // NOI18N
        mnListadoPorSexo.setText("Listado por Marcas");
        mnListadoPorSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mnListadoPorSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListadoPorSexoActionPerformed(evt);
            }
        });
        mnListados.add(mnListadoPorSexo);

        jMenuItem6.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415752_sign-up.png"))); // NOI18N
        jMenuItem6.setText("Listado por Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnListados.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1479415973_Sales-by-Payment-Method-rep.png"))); // NOI18N
        jMenuItem7.setText("Listado por vendedores");
        jMenuItem7.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnListados.add(jMenuItem7);

        mnReportes.add(mnListados);

        mnCantidades.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mnCantidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477687910_lists.png"))); // NOI18N
        mnCantidades.setText("Cantidades");
        mnCantidades.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N

        mnCantidadPersonasIngresadas.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        mnCantidadPersonasIngresadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477688138_BT_computer.png"))); // NOI18N
        mnCantidadPersonasIngresadas.setText("Cantidad de Computadores Ingresados");
        mnCantidadPersonasIngresadas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mnCantidadPersonasIngresadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCantidadPersonasIngresadasActionPerformed(evt);
            }
        });
        mnCantidades.add(mnCantidadPersonasIngresadas);

        mnReportes.add(mnCantidades);

        jMenuBar1.add(mnReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarActionPerformed
        Agregar a = new Agregar(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnAgregarActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnListadoPorSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListadoPorSexoActionPerformed

    }//GEN-LAST:event_mnListadoPorSexoActionPerformed

    private void mnCantidadPersonasIngresadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCantidadPersonasIngresadasActionPerformed
        int cont;
        cont = Helper.traerDatos(ruta).size();
        Helper.mensaje(this, "El número de Computadores ingresadas es: " + cont, 1);

    }//GEN-LAST:event_mnCantidadPersonasIngresadasActionPerformed

    private void mnListadoPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListadoPersonasActionPerformed
        ListadoComputadores lc = new ListadoComputadores(this, true);
        lc.setVisible(true);
    }//GEN-LAST:event_mnListadoPersonasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpcionesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnOpcionesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AgregarClientes a = new AgregarClientes(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AgregarFactura f = new AgregarFactura(this, true);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AgregarVendedores a = new AgregarVendedores(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ListadoClientes v = new ListadoClientes(this, true);
       v.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ListadoVendedores a = new ListadoVendedores(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnAgregar;
    private javax.swing.JMenuItem mnCantidadPersonasIngresadas;
    private javax.swing.JMenu mnCantidades;
    private javax.swing.JMenuItem mnListadoPersonas;
    private javax.swing.JMenuItem mnListadoPorSexo;
    private javax.swing.JMenu mnListados;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JMenuItem mnSalir;
    // End of variables declaration//GEN-END:variables
}
